### ISSUE TITLE
Thank You for sharing this repository! 😃 

### ISSUE THREAD

**Issue by dzintars** [larsron/packer-linux#1]
Hi,
Just rising this to say thank you. Today landed into Packer and looking for good examples and Yours definitely is the best i saw so far! :)
Was not expecting it to work out of box, but it does. Except Ansible connection which is fine for me. Personally i am looking how to build bare base image (without config) because i will run cloud-init via Terraform (dmacvicar/libvirt provider) and Ansible at later stage.
Like your file structure. I think i will take some inspiration from this repository. :)

There is an error i saw at first run.
```bash
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:43609' (RSA) to the list of known hosts.\r\nsign_and_send_pubkey: no mutual signature supported\r\ndzintars@127.0.0.1: Permission denied (publickey).", "unreachable": true}
```

Have a nice day!

P.S. Definitely close this issue.

**Comment by tenthirtyam** [comment]
Attribution should be provided to [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere) from which this repository derives much of it’s structure and content.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by larsron** [comment]
No problem. Done.
